### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by philharmonie** [joergklein/docker-nginxproxymanager#1]
Setting [this](https://github.com/joergklein/docker-nginxproxymanager#secure-the-nginx-proxy-manager) up ends up in **504 Gateway Time-out**.

Edit: Your link in your readme is not working. I am relating to the topic *Secure the NGINX Proxy Manager*.

**Comment by bener07** [comment]
I'm having the same problem

**Comment by bener07** [comment]
The docker-compose.yml file has the configuration of the database as db, which is using the docker DNS, so you need to provide the links on the file and that will solve it, at least for the latest version.
